version: '3.8'

services:
  api:
    build:
      context: musiclib
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./musiclib/.env:/.env
    environment:
      - HTTP_SERVER_ADDRESS=:8080
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=musiclib
      - POSTGRES_PORT=5432

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: musiclib
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d musiclib"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: