CREATE TABLE IF NOT EXISTS groups (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    group_name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS songs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    group_id BIGINT NOT NULL,
    song_name TEXT NOT NULL,
    release_date DATE NOT NULL,
    text TEXT NOT NULL,
    link TEXT NOT NULL,
    CONSTRAINT fk_group FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE
);

CREATE INDEX idx_group_name ON groups(group_name);
CREATE INDEX idx_song_name ON songs(song_name);